"""
    exporter config file

    * we are exporting data directly from database into output directory
    * prestashop code is not executed by exporter
    * you have to select your shop id and language for export
"""

""" prestashop id_shop, typically 1 """
SHOP_ID = None #take config from PS_SHOP_DEFAULT
SHOP_GROUP_ID = 1 #default shop group id
    #exporter was not tested with shop groups enabled
COUNTRY_ID = None #take config from PS_COUNTRY_DEFAULT

CATEGORY_URL_TEMPLATE = \
    "http://localhost/prestashop/index.php?id_category={id_category}&controller=category"
PRODUCT_URL_TEMPLATE = \
    "http://localhost/prestashop/index.php?id_product={id_product}&controller=product"
PRODUCT_URL_BASE = \
    "http://localhost/prestashop/"
IMAGE_URL_BASE = "http://localhost/prestashop/img/"
IMAGE_URL_TYPE = 'link-rewrite' #dirs or link-rewrite

""" prestashop table name prefix, default is 'ps' """
PREFIX = 'ps'

""" database name, user and password """
DB_NAME = 'prestashop'
DB_USER = 'prestashop'
DB_PASSWORD = '12345'
DB_HOST = '127.0.0.1'
DB_PORT = 3306

""" We are exporting text in one language selected by language code.

    ISO 639-1 language code (mostly identical to country's top-level domain)
    https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
    English - en
    French - fr
    Czech - cs
    Slovak - sk
    Polish - pl
    Hungarian - hu """
LANG = 'cs'

""" directory for storing export files to
    should be located on webserver so samba can see the files

    it is recommended to generate a directory name, such as
    /var/www/prestashop/samba-export/eceisoh5Bohchah5pohx
    (generated by pwgen 30) """
OUTPUT_DIRECTORY = '/var/www/prestashop/samba-export/'

"""
    Emulate SpecificPrice class, calculate discounted prices.
    If disabled, base prices without discounts will be exported.
    Note: since we are duplicating prestashop functionality, this can lead to
    errorneous calculation of discounted prices. """
SPECIFIC_PRICE = True

"""
list of orders.current_state values in samba terms
all other values are interpreted as "CREATED" state
"""

ORDER_CANCELLED = {6}
ORDER_FINISHED = {5}

"""
configurable export items
"""

PRICE_BUY = True
